export const references = {
  leadReversal: { title:'Rosenほか：Common ECG Lead Placement Errors, Part I（2014）',url:'https://ijms.pitt.edu/IJMS/article/download/95/544?inline=1',detail:'電極接続を変えて記録した原著。Resultsの腕の左右交換と胸部R波の比較を参照。図の転載なし。' },
  acs: { title:'JCS 2018：急性冠症候群（英語版2019）',url:'https://www.jstage.jst.go.jp/article/circj/advpub/0/advpub_CJ-19-0133/_html/-char/en',detail:'心電図の陰性T・Q波の観察と鑑別。治療推奨は扱いません。' },
  wellens: { title:'ACC：Wellens Syndrome Important to Consider in Chest Pain（2023）',url:'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2023/01/20/17/59/wellens-syndrome',detail:'学会の解説。胸痛の経過とV2・V3の二相性T／陰性Tの観察を参照。' },
  cardiomyopathy: { title:'NHLBI：Types of Cardiomyopathy（2024）',url:'https://www.nhlbi.nih.gov/health/cardiomyopathy/types',detail:'HCM・DCMの構造と機能の基本。' },
  takotsubo: { title:'International Expert Consensus on Takotsubo Syndrome, Part I（2018）',url:'https://iris.uniroma1.it/bitstream/11573/1659479/1/Gradir_International-Expert-Consensus-Document_2018.pdf',detail:'著者所属大学リポジトリの原文。壁運動、誘因、心電図所見を参照。図の転載なし。' },
  takotsuboTime: { title:'International Expert Consensus on Takotsubo Syndrome, Part II（2018）',url:'https://spiral.imperial.ac.uk/entities/publication/134110b0-e848-435e-8dc4-eb75700454e4',detail:'著者所属大学リポジトリの原文。Electrocardiogram節のST・T・QTの経時変化。経過や回復時期は全例同じではありません。' },
  pulmonaryEcg: { title:'Nakayamaほか：急性肺塞栓症の心電図所見に関する原著（2025）',url:'https://www.jstage.jst.go.jp/article/circrep/advpub/0/advpub_CR-25-0012/_pdf',detail:'SⅠQⅢTⅢと右前胸部T波の定義を参照。肺塞栓症患者内での重症度比較であり、一般集団の確定診断の精度へ転用していません。' },
  pericardium: { title:'ESC 2025：Myocarditis and Pericarditis',url:'https://www.myocarditisfoundation.org/wp-content/uploads/2025/09/ehaf192.pdf',detail:'学会ガイドライン原文の公開写し。5.1節の心電図所見、11.8節のタンポナーデの病態と臨床評価。' },
  pericarditisEcg: { title:'ESC：Diagnosis of acute pericarditis（2017）',url:'https://www.escardio.org/communities/councils/cardiology-practice/scientific-documents-and-publications/ejournal/volume-15/Diagnosis-of-acute-pericarditis/',detail:'ECG findings節の形と分布を参照。旧版の診断基準や治療推奨は教材へ転用していません。' },
  technology: { title:'AHA/ACCF/HRS：ECG標準化 Part I（記録技術、2007）',url:'https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.106.180200',detail:'電極の左右取り違えと鏡像右胸心の違い。' },
  conductionDisorders: { title:'NHLBI：Conduction Disorders',url:'https://www.nhlbi.nih.gov/health/conduction-disorders' },
  hyperkalemia: { title:'Royal Children’s Hospital：Hyperkalaemia',url:'https://www.rch.org.au/clinicalguide/guideline_index/Hyperkalaemia/',detail:'波形変化と、正常に見えるECGでも危険を除外できない点を参照。小児の治療基準を成人へ転用していません。' },
  hypokalemia: { title:'Royal Children’s Hospital：Hypokalaemia',url:'https://www.rch.org.au/clinicalguide/guideline_index/Hypokalaemia/',detail:'T・U・STの観察点のみ参照。投与量・治療判断を扱いません。' },
  digoxin: { title:'DailyMed：Digoxin製品表示、12.2 ECG Changes',url:'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=dcf9b23b-5840-46ff-bb61-c57a02831a03' },
  pacing: { title:'NHLBI：Pacemakers — How They Work',url:'https://www.nhlbi.nih.gov/health/pacemakers/how-it-works' },
  pacingModes: { title:'Medtronic：5392 Reference Guide',url:'https://www.medtronic.com/content/dam/medtronic-wide/public/canada/products/cardiac-vascular/cardiac-rhythm/pacing-systems/epg-5392-reference-guide.pdf',detail:'心房追跡、感知と捕捉の用語を確認。装置の操作手順を転載した教材ではありません。' },
  mvp: { title:'Medtronic：Managed Ventricular Pacing',url:'https://www.medtronic.com/en-us/healthcare-professionals/products/cardiac-rhythm/technologies/managed-ventricular-pacing.html',detail:'AAI(R)とDDD(R)の切替による自己伝導の利用。機種固有機能の例。' },
  crt: { title:'Boston Scientific：How CRT devices work',url:'https://www.bostonscientific.com/en-US/patients-caregivers/device-support/crt/how-crt-works.html' },
  atp: { title:'Medtronic：Intrinsic ATP',url:'https://www.medtronic.com/en-us/healthcare-professionals/products/cardiac-rhythm/technologies/intrinsic-atp-algorithm.html',detail:'抗頻拍ペーシングの役割を参照。製品の有効率や設定を一般化していません。' },
  blockedPac: { title: '清水ほか：非伝導性心房期外収縮と補充収縮の症例報告（2021）', url: 'https://www.jstage.jst.go.jp/article/jse/41/4/41_183/_pdf', detail: 'T波に重なるP′と非伝導性PACの観察を参照。図の転載はしていません。' },
  arrhythmiaTypes: { title: 'NHLBI：Types of Arrhythmias', url: 'https://www.nhlbi.nih.gov/health/arrhythmias/types', detail: '早期収縮・上室性／心室性不整脈の基本。' },
  aivr: { title: '松尾ほか：健診受診者における促進心室固有調律（2025）', url: 'https://www.jstage.jst.go.jp/article/ndprevmedcare/40/4/40_743/_pdf/-char/ja', detail: '原著。研究内の速度定義と、実波形による再確認方法を参照。' },
  intraventricular: { title: 'AHA/ACCF/HRS：ECG標準化 Part III（心室内伝導、2009）', url: 'https://www.infarkt.ru/f/recommendations_for_interpretation_of_the_ecg.pdf', detail: '学会声明原文の公開写し。成人の電気軸・QRS幅の基本定義。' },
  amyloid: { title: 'JCS 2020：心アミロイドーシス診療ガイドライン', url: 'https://www.jstage.jst.go.jp/article/circj/84/9/84_CJ-20-0110/_html/-char/en', detail: 'Ⅱ章3：電位・偽梗塞所見の定義と診断上の限界。治療選択の教材ではありません。' },
  conduction: { title: 'NHLBI：How the Heart Beats', url: 'https://www.nhlbi.nih.gov/health/heart/heart-beats', detail: '心臓の刺激伝導と安静時の心拍数。' },
  recording: { title: 'SCST：Recording a Standard 12-Lead Electrocardiogram（2017）', url: 'https://criticalcaretraining.ie/wp-content/uploads/2022/04/SCST_ECG_Recording_Guidelines_2017am-2.pdf', detail: '学会原文の公開写し。6章の電極位置と7章の記録条件を参照。' },
  jcs: { title: 'JCS/JHRS 2022：不整脈の診断とリスク評価（英語版2024）', url: 'https://onlinelibrary.wiley.com/doi/10.1002/joa3.13052' },
  inherited: { title: 'JCS/JHRS 2026：遺伝性不整脈の診療', url: 'https://www.j-circ.or.jp/cms/wp-content/uploads/2026/03/JCS2026_Makiyama.pdf' },
  repolarization: { title: 'AHA/ACCF/HRS：ECG標準化 Part IV（ST・T・U・QT、2009）', url: 'https://fd.org.ua/wp-content/uploads/2019/03/AHAA-CCF-HRS-Recommendations-for-the-Standardization-and-Interpretation-of-the-Electrocardiogram-Part-IV.pdf', detail: '学会声明原文の公開写し。測定法の基本を参照し、疾患の診断は現行ガイドラインと区別。' },
  pediatric: { title: 'Royal Children’s Hospital：Basic paediatric ECG interpretation', url: 'https://www.rch.org.au/clinicalguide/guideline_index/Basic_Paediatric_ECG_interpretation/' },
  mi: { title: 'Fourth universal definition of myocardial infarction（2018）', url: 'https://academic.oup.com/eurheartj/article/40/3/237/5079081' },
};
