"""Import explicitly reviewed PTB-XL records; no network access and no bulk import.

Usage: python scripts/import-ptbxl.py CSV INPUT_DIR RECORD_ID [RECORD_ID ...]
Preserves original WFDB bytes and a minimal audit trail, never patient identifiers.
Review notes must then be completed in app/content/classroom/records.ts.
"""
import ast
import csv
import hashlib
import json
from pathlib import Path
import shutil
import sys

csv_path, input_dir, *ids = sys.argv[1:]
records = {row['ecg_id']: row for row in csv.DictReader(Path(csv_path).open(encoding='utf-8'))}
output = Path(__file__).resolve().parents[1] / 'public/data/ptb-xl'
output.mkdir(parents=True, exist_ok=True)
for record_id in ids:
    row = records[str(int(record_id))]
    stem = Path(row['filename_hr']).name
    hashes = {}
    for extension in ['hea', 'dat']:
        source = Path(input_dir) / f'{stem}.{extension}'
        hashes[extension] = hashlib.sha256(source.read_bytes()).hexdigest()
        shutil.copyfile(source, output / source.name)
    keep = ['report', 'heart_axis', 'infarction_stadium1', 'infarction_stadium2', 'validated_by',
            'second_opinion', 'initial_autogenerated_report', 'validated_by_human',
            'baseline_drift', 'static_noise', 'burst_noise', 'electrodes_problems', 'extra_beats', 'pacemaker']
    metadata = {key: row[key] for key in keep}
    metadata.update({
        'ecg_id': int(record_id), 'scp_codes': ast.literal_eval(row['scp_codes']),
        'version': '1.0.3', 'sourcePath': row['filename_hr'], 'sha256': hashes,
        'source': 'https://physionet.org/content/ptb-xl/1.0.3/',
        'license': 'https://creativecommons.org/licenses/by/4.0/',
        'acquired': '2026-09-28', 'processing': 'Original WFDB bytes; no filtering, resampling or amplitude normalization.',
    })
    (output / f'{stem}.json').write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'Imported {record_id}: {stem} with source hashes and selected metadata')
